-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 11:02:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `supplierID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NULL,
  `contactInfo` VARCHAR(125) NULL,
  `address` VARCHAR(125) NULL,
  PRIMARY KEY (`supplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drug` (
  `drugID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NULL,
  `category` VARCHAR(125) NULL,
  `stock` INT NULL,
  `Supplier_supplierID` INT NOT NULL,
  PRIMARY KEY (`drugID`, `Supplier_supplierID`),
  INDEX `fk_Drug_Supplier_idx` (`Supplier_supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Drug_Supplier`
    FOREIGN KEY (`Supplier_supplierID`)
    REFERENCES `mydb`.`Supplier` (`supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `inventoryID` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NULL,
  `Drug_drugID` INT NOT NULL,
  `Drug_Supplier_supplierID` INT NOT NULL,
  PRIMARY KEY (`inventoryID`, `Drug_drugID`, `Drug_Supplier_supplierID`),
  INDEX `fk_Inventory_Drug1_idx` (`Drug_drugID` ASC, `Drug_Supplier_supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Drug1`
    FOREIGN KEY (`Drug_drugID` , `Drug_Supplier_supplierID`)
    REFERENCES `mydb`.`Drug` (`drugID` , `Supplier_supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pharmacist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pharmacist` (
  `pharmacistID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NULL,
  `contactInfo` VARCHAR(125) NULL,
  PRIMARY KEY (`pharmacistID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NULL,
  `address` VARCHAR(125) NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale` (
  `saleID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `items` TEXT(10000) NULL,
  `receipt` VARCHAR(125) NULL,
  `Pharmacist_pharmacistID` INT NOT NULL,
  `Customers_customerID` INT NOT NULL,
  `Drug_drugID` INT NOT NULL,
  `Drug_Supplier_supplierID` INT NOT NULL,
  PRIMARY KEY (`saleID`),
  INDEX `fk_Sale_Pharmacist1_idx` (`Pharmacist_pharmacistID` ASC) VISIBLE,
  INDEX `fk_Sale_Customers1_idx` (`Customers_customerID` ASC) VISIBLE,
  INDEX `fk_Sale_Drug1_idx` (`Drug_drugID` ASC, `Drug_Supplier_supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Pharmacist1`
    FOREIGN KEY (`Pharmacist_pharmacistID`)
    REFERENCES `mydb`.`Pharmacist` (`pharmacistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Customers1`
    FOREIGN KEY (`Customers_customerID`)
    REFERENCES `mydb`.`Customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Drug1`
    FOREIGN KEY (`Drug_drugID` , `Drug_Supplier_supplierID`)
    REFERENCES `mydb`.`Drug` (`drugID` , `Supplier_supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerOrder` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `quantity` INT NULL,
  `status` VARCHAR(125) NULL,
  `Customers_customerID` INT NOT NULL,
  PRIMARY KEY (`orderID`, `Customers_customerID`),
  INDEX `fk_CustomerOrder_Customers1_idx` (`Customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerOrder_Customers1`
    FOREIGN KEY (`Customers_customerID`)
    REFERENCES `mydb`.`Customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SalesAssociate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SalesAssociate` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NULL,
  `contactInfo` VARCHAR(125) NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Return`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Return` (
  `returnID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `reason` TEXT(10000) NULL,
  `receipt` VARCHAR(50),
  `customer` VARCHAR(125) NULL,
  `SalesAssociate_employeeID` INT NOT NULL,
  PRIMARY KEY (`returnID`),
  INDEX `fk_Return_SalesAssociate1_idx` (`SalesAssociate_employeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Return_SalesAssociate1`
    FOREIGN KEY (`SalesAssociate_employeeID`)
    REFERENCES `mydb`.`SalesAssociate` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderItem` (
  `orderItemID` INT NOT NULL AUTO_INCREMENT,
  `productInformation` TEXT(10000) NULL,
  `instructions` TEXT(10000) NULL,
  `Drug_drugID` INT NOT NULL,
  `Drug_Supplier_supplierID` INT NOT NULL,
  PRIMARY KEY (`orderItemID`),
  INDEX `fk_OrderItem_Drug1_idx` (`Drug_drugID` ASC, `Drug_Supplier_supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_Drug1`
    FOREIGN KEY (`Drug_drugID` , `Drug_Supplier_supplierID`)
    REFERENCES `mydb`.`Drug` (`drugID` , `Supplier_supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `purchaseDate` DATE NULL,
  `OrderItem_orderItemID` INT NOT NULL,
  PRIMARY KEY (`orderID`, `OrderItem_orderItemID`),
  INDEX `fk_Order_OrderItem1_idx` (`OrderItem_orderItemID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_OrderItem1`
    FOREIGN KEY (`OrderItem_orderItemID`)
    REFERENCES `mydb`.`OrderItem` (`orderItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
